export {
    PostSkeleton,
    PostListSkeleton,
    TopPostSkeleton,
    TrendingListSkeleton,
    CategoryListSkeleton,
    PostCardTwoSkeleton,
    PostCardTwoListSkeleton,
    PostCardThreeSkeleton,
    PostCardThreeListSkeleton,
    RelatedArticleSkeleton,
    RelatedArticleListSkeleton,
    PostBannerSkeleton,
    PostBannerTwoSkeleton,
    PostBannerThreeSkeleton,
    PostBannerFourSkeleton,
    PostContentSkeleton,
    PostContentThreeSkeleton,
    PostSidebarTwoSkeleton,
    RelatedArticleTwoSkeleton,
    RelatedArticleTwoListSkeleton
} from "./PostSkeleton";
